name: Rebuild Cookbook Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Hook
        env:
          DEPLOY_HOOK_URL:           
          # Go to your GitHub repository
          
          # Click on "Settings" → "Secrets and variables" → "Actions"
          
          # Click "New repository secret"
          
          # Name: WEBSITE_DEPLOY_HOOK_URL
          
          # Value: <your-deploy-hook-url>
          
        run: curl -X POST "$DEPLOY_HOOK_URL"
